version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: productdb
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: http://elasticsearch:9200

      